### PR TITLE
Allow region to be forced in query parameter

### PR DESCRIPTION
**Pull request by justinsb**
This isn't a security issue, because we rely on a client-side redirect
anyway, and this is convenient for testing and maybe for clients that
want to identify as being close to a particular region.

### CODE REVIEW

**Comment by justinsb** [comment]
~Lint crash is bug in golang-ci, workaround in #17~  Now fixed :-)

**Comment by ameukam** [comment]
we should probably put this behind a debug flag ?

**Comment by justinsb** [comment]
> we should probably put this behind a debug flag ?

We can, but I'm not sure I see any harm of having this in prod, and it could help us understand what's going on.  Happy to add a debug env var though, so I'll do it and we can see how we feel.

**Comment by justinsb** [comment]
Added a simple feature-flag support, so we can turn this off and on by environment (along with other future features)

**Pull request merged**
