### PR TITLE
Run with specific version of go

### PR DESCRIPTION
**Pull request by justinsb**
This ensures a more reproducible build.

### CODE REVIEW

**Comment by justinsb** [comment]
This is particularly important because our linter is broken with 1.20, but it looks like the base image was updated to go 1.20: https://github.com/golangci/golangci-lint/pull/3414

**Comment by ameukam** [comment]
/lgtm
/hold

Remove the hold when ready

**Comment by justinsb** [comment]
Thank you - this will unblock the other PRs so...

/hold cancel

**Pull request merged**
